dist: trusty
sudo: required
language: node_js
node_js:
  - '8'
addons:
  chrome: stable
cache:
  directories:
     - ./node_modules
before_script:
  - npm install -g @angular/cli@6.0.8
script: 
  - xvfb-run -a npm run test -- --watch=false --browsers=ChromeNoSandbox
  - xvfb-run -a npm run e2e -- --protractor-config=protractor-ci.conf.js
before_deploy:
  - ng build --prod --aot --delete-output-path=false --base-href "https://vieraslajit.github.io/Vieraslajit/"

branches:
  only:
  - master
  - pages-test
  