dist: trusty
sudo: false
language: node_js
node_js:
  - '8'
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
cache:
  directories:
     - ./node_modules
before_script:
  - npm install -g @angular/cli
script: 
  # Use Chromium instead of Chrome.
  - export CHROME_BIN=chromium-browser
  - xvfb-run -a npm run test -- --watch=false --browsers=Chrome
  - xvfb-run -a npm run e2e -- --protractor-config=protractor-ci.conf.js
before_deploy:
  - ng build --prod --aot --no-delete-output-path -bh "https://vieraslajit.github.io/Vieraslajit/"
branches:
  only:
  - master
  - pages-test
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  local_dir: dist
  on:
    branch:
      - pages-test
      - master